defmodule Boogaloo.Repo.Migrations.AddRatingToBlogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:blogs) do
      add :rating, :bigint, null: false, default: 3
    end
  end

  def down do
    alter table(:blogs) do
      remove :rating
    end
  end
end
