defmodule Boogaloo.Repo.Migrations.AddBlogsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:blogs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :user_id, references(:users, column: :id, name: "blogs_user_id_fkey", type: :uuid),
        null: false

      add :published_at, :utc_datetime
      add :body, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:blogs, "blogs_user_id_fkey")

    drop table(:blogs)
  end
end